### PR TITLE
Edit: Inaccurate Buddha quotes

### PR DESCRIPTION
**Pull request by khemarato**
The quotable database contains a large number of mistaken Buddha quotes.

Some are slight misquotations, but most are entirely made-up. Many of these are anodyne but a fair number significantly misrepresent the man and his religion, followed by roughly half a billion people worldwide.

In this PR, I've gone through every quote attributed to the Buddha, and have either replaced it with the original quote or removed the quote entirely if it was made up out of whole cloth.

Below you will find links to the research done for each quote, identifying its history and how it came to be misattributed to the Buddha:

## Fixed Quotes:
- https://fakebuddhaquotes.com/happiness-comes-when-your-work-and-words-are-of-benefit-to-yourself-and-others/
- https://fakebuddhaquotes.com/chaos-is-inherent-in-all-compounded-things-strive-on-with-diligence/
- https://fakebuddhaquotes.com/we-are-shaped-by-our-thoughts-we-become-what-we-think/
- https://fakebuddhaquotes.com/if-you-propose-to-speak-always-ask-yourself-is-it-true-is-it-necessary-is-it-kind/
- https://fakebuddhaquotes.com/as-a-candle-cannot-burn-without-fire-so-men-cannot-live-without-a-spiritual-life/
- https://fakebuddhaquotes.com/peace-comes-from-within-do-not-seek-it-without/
- https://fakebuddhaquotes.com/your-work-is-to-discover-your-world-and-then-with-all-your-heart-give-yourself-to-it/
- https://fakebuddhaquotes.com/he-who-experiences-the-unity-of-life/
- https://fakebuddhaquotes.com/however-many-holy-words-you-speak-however-many-you-read-what-good-will-they-do-you-if-you-do-not-act-on-them/
- https://fakebuddhaquotes.com/do-not-overrate-what-you-have-received-or-envy-others-he-who-envies-others-does-not-obtain-peace-of-mind/
- https://fakebuddhaquotes.com/the-way-is-not-in-the-sky-the-way-is-in-the-heart/
- https://fakebuddhaquotes.com/you-yourself-as-much-as-anybody-in-the-entire-universe-deserve-your-love-and-affection/
- https://fakebuddhaquotes.com/a-jug-fills-drop-by-drop/

## Removed Quotes:
- https://fakebuddhaquotes.com/you-cannot-travel-the-path-until-you-have-become-the-path-itself/
- https://fakebuddhaquotes.com/you-will-not-be-punished-for-your-anger-you-will-be-punished-by-your-anger/
- https://fakebuddhaquotes.com/an-idea-that-is-developed-and-put-into-action-is-more-important-than-an-idea-that-exists-only-as-an-idea/
- https://fakebuddhaquotes.com/if-you-light-a-lamp-for-someone-else-it-will-also-brighten-your-own-path/
- https://fakebuddhaquotes.com/it-is-better-to-travel-well-than-to-arrive/
- https://fakebuddhaquotes.com/just-as-treasures-are-uncovered-from-the-earth-so-virtue-appears-from-good-deeds-and-wisdom-appears-from-a-pure-and-peaceful-mind-to-walk-safely-through-the-maze-of-human-life-one-needs-the-ligh/
- https://fakebuddhaquotes.com/there-are-only-two-mistakes-one-can-make/
- https://fakebuddhaquotes.com/he-is-able-who-thinks-he-is-able/
- https://fakebuddhaquotes.com/the-foot-feels-the-foot-when-it-feels-the-ground/
- https://fakebuddhaquotes.com/in-separateness-lies-the-worlds-great-misery-in-compassion-lies-the-worlds-true-strength/
- https://fakebuddhaquotes.com/every-human-being-is-the-author-of-his-own-health-or-disease/
- https://fakebuddhaquotes.com/to-live-a-pure-unselfish-life-one-must-count-nothing-as-ones-own-in-the-midst-of-abundance/
- https://fakebuddhaquotes.com/holding-on-to-anger-is-like-grasping-a-hot-coal-with-the-intent-of-harming-another-you-end-up-getting-burned/
- https://fakebuddhaquotes.com/no-matter-how-hard-the-past-you-can-always-begin-again/
- https://fakebuddhaquotes.com/when-you-realize-how-perfect-everything-is-you-will-tilt-your-head-back-and-laugh-at-the-sky/
- https://fakebuddhaquotes.com/the-thought-manifests-as-the-word-the-word-manifests-as-the-deed-the-deed-develops-into-habit-and-habit-hardens-into-character/
- https://fakebuddhaquotes.com/you-only-lose-what-you-cling-to/
- https://fakebuddhaquotes.com/remembering-a-wrong-is-like-carrying-a-burden-on-the-mind/
- https://fakebuddhaquotes.com/in-the-sky-there-is-no-distinction-of-east-and-west/
- https://fakebuddhaquotes.com/if-we-could-understand-a-single-flower-we-could-understand-the-whole-universe/
- https://fakebuddhaquotes.com/no-one-saves-us-but-ourselves-no-one-can-and-no-one-may-we-ourselves-must-walk-the-path/
- https://fakebuddhaquotes.com/work-out-your-own-salvation-do-not-depend-on-others/
- https://fakebuddhaquotes.com/the-instant-we-feel-anger-we-have-already-ceased-striving/
- https://fakebuddhaquotes.com/your-body-is-precious-it-is-your-vehicle-for-awakening-treat-it-with-care/
- https://fakebuddhaquotes.com/the-only-real-failure-in-life-is-not-to-be-true-to-the-best-one-knows/

Thanks to @thesunshade who kindly pointed out that this database has been the source of some misinformation on social media.

### CODE REVIEW

**Comment by khemarato** [comment]
You'll find 61 new, authentic Buddha quotes in https://github.com/quotable-io/data/issues/11 which I hope makes up for all the quotes removed in this PR 😁

**Comment by lukePeavey** [comment]
Thank you for all the work you did on this.  I'm sorry if these quotes caused any offense.

> Some are slight misquotations, but most are entirely made-up. Many of these are anodyne but a fair number significantly misrepresent the man and his religion, followed by roughly half a billion people worldwide.

Most of the quotes in the database were pulled from various online sources using automated tools.  I have not personally reviewed all of them for accuracy and quality.  Many of the quotes you removed appear on other quotations websites (such [BrainyQuotes](https://www.brainyquote.com)) which is where I found them. 



I appreciate your help researching and correcting these issues.  I will merge your changes and update the database

**Comment by thesunshade** [comment]
Thank you so much!

Would you be so kind as to point me towards the databases you got the original quotes from?

**Comment by khemarato** [comment]
Thank you for the quick merge! 😊

**Comment by lukePeavey** [comment]
@thesunshade Most of the quotes in the database have been pulled from quotations sites (mainly the two listed below).  A smaller number of quotes have been contributed by other people (you can find those in the pull requests on this repository,  and the Discussions area of the [Quotable](https://github.com/LukePeavey/Quotable) repository. 

- https://www.brainyquote.com/
- http://www.quotationspage.com/


The database also includes some quotes that were taken from another project I found on Github 7 or 8 years ago.  I don't remember what that repository was called.  It consisted of a JSON file containing a list of roughly 800 quotes.   I used that as the starting point for an early version of this project (at the time, it was not intended for public use).  Most of those quotes have since been removed. But that may be the source of some of the inaccurate quotes.

**Comment by thesunshade** [comment]
> pulled from quotations sites

Thanks for all the information! And for correcting your service.

I wonder if you and your team have any procedures in place to ensure that these fake quotes don't find their way back in to the database.

**Comment by lukePeavey** [comment]
@thesunshade All changes to the database are made through this repository.   The only way quotes can be added or modified is through a pull request or issue on this repository.  

I am not planning to add or change any quotes by the buddha in the future.  If there are any pull requests that add or change Buddha quotes, I will consult with you or @buddhist-uni before merging any changes.

**Comment by lukePeavey** [comment]
@thesunshade / @buddhist-uni 

The changes you submitted in #10 and  #11 have been merged and synced to the live database.  

The following API request will return all quotes by the Buddha, sorted by date modified (with recently added / modified quotes at the top). 

https://api.quotable.io/quotes?author=the-buddha&limit=150

Thank you again for this contribution.   Please feel free to open a new issue or pull request if you would like to make any additional changes.

**Pull request merged**
